# Generated by Django 3.2.7 on 2021-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_date',
            field=models.DateField(null=True),
        ),
    ]
