# Generated by Django 3.2.7 on 2021-10-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publishing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishing_date',
        ),
    ]
